name: Super-Linter

on: push

jobs:
Super-Linter:
name: Lint code base
runs-on: ubuntu-latest
steps: 
- name: Checkout code
uses: action/checkout@v2
- name: Run Super-Linter
uses: github/super-linter@v3
evn: 
DFFAULT_BRANCH: main
GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
